name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  packer_build:
    name: Build image for Linode
    runs-on: ubuntu-latest
    environment: build
    permissions:
      contents: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PACKER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_API_TOKEN }} # Avoid rate limiting, see https://developer.hashicorp.com/packer/docs/configure#packer_github_api_token
      LINODE_TOKEN: ${{ secrets.LINODE_TOKEN }}
      RELEASE_CHANNEL: ${{ github.event_name == 'push' && 'edge' || format('dev-{0}', github.head_ref) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Detect changes
        id: detect_changes
        env:
          BASE_SHA: ${{ github.event.pull_request.base.sha || github.event.before }}
          HEAD_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
        run: |
          set -e -o pipefail
          echo "changed=$(git diff --name-only $BASE_SHA $HEAD_SHA | grep -E '^(Makefile|packer/)' | wc -l)" >> $GITHUB_OUTPUT
      - name: Log changes
        run: |
          echo "Changes to packer/: ${{ steps.detect_changes.outputs.changed }}"
      - name: Setup packer
        uses: hashicorp/setup-packer@v3.1.0
        with:
          version: v1.14.2
      - name: Build image (${{ env.RELEASE_CHANNEL }})
        if: ${{ steps.detect_changes.outputs.changed > 0 }}
        run: make BUILD=linode CHANNEL=${RELEASE_CHANNEL}
